mouse:
  url:
    launcher:
      # This depends on your OS, on Mac it’s `open`
      program: open
    modifiers: Command

font:
  size: 12.0
  normal:
    family: "MesloLGS NF"

key_bindings:
  - { key: Right, mods: Alt, chars: "\x1BF" }
  - { key: Left,  mods: Alt, chars: "\x1BB" }
  - { key: Q,     mods: Command, action: None }
  - { key: W,     mods: Command, action: None }

colors:
  # Default colors
  primary:
    background: '0x010b17'
    foreground: '0xebddf4'

  # Cursor colors
  cursor:
    text:   '0x000000'
    cursor: '0x38ff9c'

  # Normal colors
  normal:
    black:   '0x0b3b61'
    red:     '0xff3a3a'
    green:   '0x52ffcf'
    yellow:  '0xfff383'
    blue:    '0x1376f8'
    magenta: '0xc792ea'
    cyan:    '0xff5dd4'
    white:   '0x15fca2'

  # Bright colors
  bright:
    black:   '0x62686c'
    red:     '0xff54b0'
    green:   '0x73ffd8'
    yellow:  '0xfcf4ad'
    blue:    '0x378dfe'
    magenta: '0xae81ff'
    cyan:    '0xff69d7'
    white:   '0x5ffbbe'
